channels:
- conda-forge
dependencies:
- atomistics =0.3.5
- h5py =3.15.1
- lammps =2024.08.29=*openmpi*
- pandas =2.3.3
- pylammpsmpi =0.3.8
- jinja2 =3.1.6
- iprpy-data =2023.07.25
- pyiron_lammps =0.5.2
